image: ubuntu:rolling

before_script:
  - apt-get update -qq && apt-get install -y -qq python3 python3-numpy ipython3 python3-setuptools python3-pip python3-pytest
  - pip3 install math3d

tests:
  script:
    - python3 test_base.py
